version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: users_db
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
